endpoint:
  url: https://google.com
  method: GET
  timeout: 1
  expectation:
    - type: HTTP_STATUS
      status: 200
    - type: LATENCY
      threshold: 1
    - type: REGEX
      regex: '.*(<body).*'
cachet:
  api_url: https://demo.cachethq.io/api/v1
  token: my_token
  component_id: 1
  #metric_id: 1
  action:
    - CREATE_INCIDENT
    - UPDATE_STATUS
  metric_milliseconds: true
frequency: 30
